stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  


build-image:
  image: docker:24.0.2   
  stage: build
  services:
    - docker:24.0.2-dind  
  script:
    - echo "Building Docker image..."
    - docker info
    - docker pull alpine:latest