- name: Prepare single host with common tools
  hosts: servers
  become: yes
  vars:
    common_packages:
      - curl
      - htop
      - wget
    remove_packages:
      - nano           
      - apache2
      - htop
  tasks:


    - name: Remove unwanted packages
      ansible.builtin.apt:
        name: "{{ remove_packages }}"
        state: absent
        purge: yes
      when: remove_packages | length > 0

    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present

- name: Prepare single host with common tools 2
  hosts: servers2
  become: yes
  vars:
    common_packages:
      - curl
      - htop
      - wget
    remove_packages:
      - nano           
      - apache2
      - htop
  tasks:

    - name: Remove unwanted packages
      ansible.builtin.apt:
        name: "{{ remove_packages }}"
        state: absent
        purge: yes
      when: remove_packages | length > 0

    - name: Install common packages
      ansible.builtin.apt:
        name: "{{ common_packages }}"
        state: present
      when:  ansible_facts['os_family'] == 'Debian'
