stages:
  - build
  - test


build-job:
  image: node:14
  stage: build
  script: | 
    cd vote
    echo "build vote"
    apt-get update && \ apt-get install -y --no-install-recommends curl && \ rm -rf /var/lib/apt/lists/*


