---

- name: Remove Nginx
  include_tasks: remove.yml
  tags:
    - cleanUp

- name: Install Nginx
  include_tasks: build.yml
  tags:
    - build

- name: Configure Nginx
  include_tasks: configure.yml
  tags:
    - configure
