---
- name: Install NGINX
  ansible.builtin.package:
    name: "{{ nginx_pkg }}"
    state: present
  notify: Restart NGINX

- name: Ensure web root exists
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"

- name: Copy logo
  ansible.builtin.copy:
    src: logo.png
    dest: "{{ web_root }}/logo.png"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "0644"

- name: Deploy landing page
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "{{ mode }}"
