- name: Install Nginx
  hosts: servers
  become: yes
  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes



  roles:
    - role: install-nginx